### ISSUE TITLE
How to update apt repositeries before running Debian based CI

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#100]
Sometimes the Debian packaging fails because some dependencies are not found:

```
$ monci ci -s debian-gbp-release --debug --branch TAG ubuntujammy REPOURL
system.ubuntujammy stdout: The following packages have unmet dependencies:
system.ubuntujammy stdout:  builddeps:./ : Depends: python3-dballe but it is not installable
```

Current workaround:

```
$ monci run --maintenance ubuntujammy apt update
```

I don't know if there are better solutions.

**Comment by spanezz** [comment]
Now `monci ci` will always update/upgrade the container before the build. I added a `monci ci --quick` option to skip this while doing development
