### ISSUE TITLE
test errors on F38/F40 builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/moncic-ci#107]
https://simc.arpae.it/moncic-ci/moncic-ci/last/main/fedora40/build.log

(mainly ` ModuleNotFoundError: No module named 'moncic.source.lint'`)

**Comment by spanezz** [comment]
It should now be fixed. The linter is currently less complete than it used to be, as some parts still need porting to the refactored code. The rest of the functionality should be there
