### ISSUE TITLE
problemi ricerca del file `.spec` nel buildscript

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/moncic-ci#42]
Premessa: il buildscript ora è integrato in moncic-ci legato all'opzione `--build-style arpa` (vedi #6 per panoramica storica).

L'originale cercava il file spec per il build in due posti distinti in cascata modificando di conseguenza il comportamento del build, pezzo rilevante:
```
if [[ $specfile =~ ^./fedora/SPECS/ ]]
then
    # Convenzione SIMC per i repo upstream
    [[ -d fedora/SOURCES ]] && find fedora/SOURCES -type f -print0 | xargs -0 -I{} cp {} ~/rpmbuild/SOURCES/
    git archive --prefix=$pkgname/ --format=tar HEAD | gzip -c > ~/rpmbuild/SOURCES/$pkgname.tar.gz
    spectool -g -R --define "srcarchivename $pkgname" $specfile
    rpmbuild -ba --define "srcarchivename $pkgname" $specfile
else
    # Convenzione per i repo con solo rpm
    find . -type f -name "*.patch" -maxdepth 1 -print0 | xargs -0 -I{} cp {} ~/rpmbuild/SOURCES/
    spectool -g -R $specfile
    rpmbuild -ba $specfile
fi
```

L'attuale buildscript sembrerebbe gestire solo il primo caso, cercando in `*/SPECS/*.spec`, fallendo quando il repository ha lo specfile nella root, vedi ad es.:
https://simc.arpae.it/moncic-ci/eccodes-rpm/202205091640/master/centos8/build.log

**Comment by brancomat** [comment]
Purtroppo la pr #43 sembra aver introdotto un bug che crea problemi a tutti i build:
su un `TypeError: 'module' object is not callable`
(log completi: https://simc.arpae.it/moncic-ci/libemos-rpm/202205130748/master/centos8/build.log)

(se preferite trattare la cosa in issue separata ditemelo che la scorporo)

**Comment by edigiacomo** [comment]
Scusa, mi era rimasta una modifica che non avevo pushato: a mia parziale discolpa, non ho ancora configurato sulla nuova macchina le info git su prompt e vado ormai col pilota automatico.
