### ISSUE TITLE
Relation between Container and ContainerBase classes

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#58]
It seems that [`moncic.container.Container`](https://github.com/ARPA-SIMC/moncic-ci/blob/782e639df02f3f1d5b47c17ec6c609183b67f7a8/moncic/container.py#L309) is an abstract class but it's never used. The class [`moncic.container.ContainerBase`](https://github.com/ARPA-SIMC/moncic-ci/blob/782e639df02f3f1d5b47c17ec6c609183b67f7a8/moncic/container.py#L376) seems a good candidate to inherit from it. Some hints:

- `Container` declares the empty methods `run`, `run_callable` and `run_shell`.
- [`ContainerBase.run_shell` calls `self.run` and `self.run_callable`](https://github.com/ARPA-SIMC/moncic-ci/blob/782e639df02f3f1d5b47c17ec6c609183b67f7a8/moncic/container.py#L431-L432), but these two methods are not implemented.
- [`moncic.system.System.create_container` declares to return a `Container`, but instead it returns `NspawnContainer` which is a subclasss of `ContainerBase`](https://github.com/ARPA-SIMC/moncic-ci/blob/782e639df02f3f1d5b47c17ec6c609183b67f7a8/moncic/system.py#L236-L245).
- `NspawnContainer` implements `forward_user`, `get_root` and `binds` methods like `Container` but inherits from `ContainerBase`.

I guess that `ContainerBase` should inherit from `Container` or the two classes should be merged in one.

**Comment by spanezz** [comment]
That is intended, as `Container` is a `Protocol` used for type checking. See [PEP0544](https://peps.python.org/pep-0544/), and for example https://auth0.com/blog/protocol-types-in-python/ and https://towardsdev.com/define-interfaces-in-python-with-protocol-classes-4aea7e940e44?gi=7e118c18eae1

**Comment by spanezz** [comment]
It may be that the Protocol definition got out of sync with the implementation and you're seeing mypy complain?

**Comment by edigiacomo** [comment]
Thank you, I didn't know the `Protocol` class, very nice: this explains the implicit relation between `NspawnContainer` and `Container`.

Unofortunately, a problem still persists: `ContainerBase.run_shell` tries to invoke `self.run` and `self.run_callable` that are not declared in the class itself (see https://github.com/ARPA-SIMC/moncic-ci/blob/782e639df02f3f1d5b47c17ec6c609183b67f7a8/moncic/container.py#L431-L432):

```
$ mypy moncic/container.py
...
moncic/container.py:431: error: "ContainerBase" has no attribute "run_callable"
moncic/container.py:432: error: "ContainerBase" has no attribute "run"
...
```

> It may be that the Protocol definition got out of sync with the implementation and you're seeing mypy complain?

IIUC, `Container` should be a base class for `ContainerBase` too, because it needs `run_callable` and `run` methods. This relation can be implemented through inheritance or defining the two methods in `ContainerBase`.
