### ISSUE TITLE
Cannot disable storing of artifacts

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#60]
Artifact storing cannot be disabled from command line, because the default is `..` https://github.com/ARPA-SIMC/moncic-ci/blob/v0.7-1/moncic/ci.py#L130

**Comment by spanezz** [comment]
Good catch! The default of `..` is the default in Debian, but since Moncic-CI wants to be generic in its work, and `..` has always been a stupid default even in Debian, I'm very happy for your patch!
