### ISSUE TITLE
ImageStorage and subclasses constructor

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/moncic-ci#62]
ImageStorage constructor wants a Session object as first argument (https://github.com/ARPA-SIMC/moncic-ci/blob/v0.7-1/moncic/imagestorage.py#L319) but its subclasses wants a Moncic object as the first argument and call the parent constructor using this as first argument.

```
moncic/imagestorage.py:361: error: Argument 1 to "__init__" of "ImageStorage" has incompatible type "Moncic"; expected "Session"
moncic/imagestorage.py:374: error: Argument 1 to "__init__" of "ImageStorage" has incompatible type "Moncic"; expected "Session"
```

Session and Moncic seems interchangeable in this context, then I don't know what's the better fix.

**Comment by spanezz** [comment]
Good catch! Session is the right one, all the Moncic-typed arguments are effectively pass-through
