### ISSUE TITLE
Build pacchetti debian con git-buildpackage

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/moncic-ci#63]
Se durante il build per debian si vede che il pacchetto usa git-buildpackage, usarlo invece di creare il source package a mano

**Comment by edigiacomo** [comment]
Per testare l'upstream branch associato ad un certo debian branch, il workflow proposto al SIMC è riassunto in questo script https://gist.github.com/edigiacomo/9baf8541ba6110d19afc847b6a71ea78: in sostanza, si fa un merge locale dell'upstream branch nel debian branch e poi si lancia `moncic ci` per verificare se l'upstream branch è pacchettizzabile. Questo passaggio potrebbe essere eseguito automaticamente da `moncic ci` stesso con il builder `debian`: per la CI automatica non ci sarebbero grosse differenze, ma nel caso di test lanciati localmente potrebbe risultare invece macchinoso dover fare tutte le volte queste operazioni (e poi resettarle alla fine del test). L'unico dubbio che ho è se il workflow è sufficientemente generico e non troppo ritagliato sulle esigenze del SIMC.
