### ISSUE TITLE
`moncic ci`: require system as first argument

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/moncic-ci#73]
Since `--system` always needs to be specified, require it as a first argument, and drop the `-s`/`--system` argument.

`-s` can then be recycled as short for `--build-style`.

Since this is a change of command line API, we need to agree first that it is doable

**Comment by edigiacomo** [comment]
Fine for me. On the next update of moncic-ci, we just have to remember to modify an internal program that uses it (`InfoContinuousIntegrationMoncicCI`).
