### ISSUE TITLE
failed tests on copr builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/moncic-ci#95]
see:
https://download.copr.fedorainfracloud.org/results/simc/stable/fedora-36-x86_64/05922007-moncic-ci/builder-live.log.gz

main error:
```
stat: cannot read file system information for '/var/lib/machines': No such file or directory
```
I noticed on a virtual machine that without `systemd-container` package there's no `/var/lib/machines` and tests fails. So I added `systemd-container` to build requirements (although the same tests that failed were simply skipped after the installation).
On copr build environment, even installing  `systemd-container` package there's no  `/var/lib/machines` path because of reasons so all related tests fail.
I'm not sure what's the best course of action here, maybe skipping some test with a warning if `/var/lib/machines` is not present?

**Comment by spanezz** [comment]
From last reports is seems this is now fixed
